jupyterlab:
        build: .
        ports:
                - "8888:8888"
        volumes:
                - ~/workspace:/workspace
        entrypoint: sh -c 'jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --notebook-dir=/workspace --allow-root'

